// ui/src/Login.jsx
import React from "react";

function Login () {
    return (<form method="post">
        <div className="form-group col-6">
            <label htmlFor="inputUsername">
                Username
            </label>
            <input type="text" className="form-control" id="inputUsername" placeholder="Enter username" name="username"/>
        </div>
        <div className="form-group col-6">
            <label htmlFor="inputPassword">
                Password
            </label>
            <input type="text" className="form-control" id="inputPassword" placeholder="Password" name="password"/>
        </div>
        <button type="submit" className="btn btn-outline-info">Login</button>
    </form>)
}

export default Login;

// ui/src/components/Login.vue
<template>
  <form v-on:submit.prevent="onLogin">
    <div v-if="error">{{error}}</div>
    <label>Username</label><input type="text" v-model.trim="username"/>
    <label>Password</label><input type="password" v-model.trim="password"/>
    <button type="submit" v-bind:disabled="isLoginDisabled()">Login</button>
  </form>
</template>

<script>
  import { login } from '../utils/client'

  export default {
    name: 'Login',
    data () {
      return {
        username: '',
        password: '',
        error: ''
      }
    },
    methods: {
      isLoginDisabled: function () {
        return !(this.username && this.password)
      },
      onLogin: function () {
        login(this.username, this.password)
      }
    }
  }
</script>
